'use client';
import IndiaReachMap from '../components/IndiaReachMap';
import { useState } from 'react';
import { ArrowUpRight, ChevronRight, MapPin, Menu, X, MessageCircle } from 'lucide-react';

const cities=[{id:'delhi',name:'Delhi',region:'Delhi NCR',count:145,x:405,y:125},{id:'lucknow',name:'Lucknow',region:'Uttar Pradesh',count:120,x:475,y:225},{id:'kanpur',name:'Kanpur',region:'Uttar Pradesh',count:105,x:438,y:245},{id:'bhopal',name:'Bhopal',region:'Madhya Pradesh',count:85,x:355,y:355}];
const imgs={left:'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1400&q=85',right:'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=1400&q=85'};
function Reach(){const [active,setActive]=useState('lucknow');return <section className="reach" id="reach"><div className="section-intro"><p className="eyebrow">02 — THE REACH</p><h2>Threads that travel<br/><i>farther.</i></h2><p className="intro-copy">From our floor in Surat, a trusted textile network stretches north and central. Every dot is a boutique, every route a relationship.</p><a className="text-link" href="#partner">Explore the full network <ArrowUpRight size={15}/></a></div><div className="map-wrap"><IndiaReachMap /></div><div className="city-ledger">{cities.map(c=><button key={c.id} className={active===c.id?'active':''} onMouseEnter={()=>setActive(c.id)} onFocus={()=>setActive(c.id)} onClick={()=>setActive(c.id)}><span><b>0{cities.indexOf(c)+1}</b>{c.name}</span><small>{c.region}<br/><strong>{c.count}</strong> boutiques · since 201{cities.indexOf(c)+1}</small><ChevronRight size={16}/></button>)}<div className="ledger-total"><span>NETWORK TOTAL</span><b>500+</b></div></div></section>}
function App(){const [menu,setMenu]=useState(false);return <main><header><div className="rail"><span>Wholesale enquiries · <b>+91 98251 44001</b></span><span>Visit the Surat showroom <i>↗</i></span><span>Download catalogue <i>↗</i></span></div><nav><a className="logo" href="#">MAA <em>SHEETLA</em><small>AGENCY · SURAT</small></a><div className={`navlinks ${menu?'open':''}`}><a href="#catalogue">Catalogues</a><a href="#reach">Reach</a><a href="#craft">Our craft</a><a href="#partner">Partner with us</a></div><button className="menub" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><a className="nav-cta" href="#partner">Start a conversation <ArrowUpRight size={15}/></a></nav></header><section className="hero"><div className="hero-panel maa"><div className="panel-top"><span>✳</span><span>01 / 02</span></div><div className="hero-copy"><p className="eyebrow">MAA SHEETLA · ESTABLISHED 2010</p><h1>Maa<br/><i>Sheetla</i></h1><p>The named counter. Sarees, lehengas, suits and garments for boutiques that sell by label.</p><a className="hero-link" href="#catalogue">See the catalogue <ArrowUpRight size={16}/></a></div></div><div className="hero-panel sunrise"><div className="panel-top"><span>✳</span><span>02 / 02</span></div><div className="hero-copy"><p className="eyebrow">SUNRISE TEX FAB · ESTABLISHED 2010</p><h1>Sunrise<br/><i>Tex Fab</i></h1><p>The volume counter. The same four catalogues, priced and packed for the floor.</p><a className="hero-link" href="#catalogue">See the catalogue <ArrowUpRight size={16}/></a></div></div><div className="hero-tag">TWO FIRMS, ONE FLOOR <span>·</span> MAA SHEETLA AGENCY</div></section><section className="stats"><div><b>2010</b><span>ESTABLISHED</span></div><div><b>500<span>+</span></b><span>BOUTIQUES</span></div><div><b>04</b><span>CATALOGUES</span></div><div><b>4</b><span>STATES AND COUNTING</span></div></section><Reach/><section className="catalogue" id="catalogue"><div><p className="eyebrow">03 — THE CATALOGUE</p><h2>Made for the<br/><i>counter.</i></h2></div><div className="cat-grid">{['Sarees','Lehengas','Suits','Garments'].map((x,i)=><a href="#partner" key={x} className={`cat cat${i}`}><span>0{i+1} / 04</span><h3>{x}</h3><small>View collection <ArrowUpRight size={14}/></small></a>)}</div></section><section className="partner" id="partner"><p className="eyebrow">04 — FOR THE RIGHT STOCKIST</p><h2>Let’s put the<br/><i>right pieces</i><br/>on your floor.</h2><a className="button" href="https://wa.me/919825144001?text=Hello%20Maa%20Sheetla%20Agency%20%E2%80%94%20I'm%20enquiring%20about%20your%20catalogue.">Enquire on WhatsApp <ArrowUpRight size={16}/></a></section><footer><div className="logo">MAA <em>SHEETLA</em><small>AGENCY · SURAT</small></div><p>Two firms. One floor.<br/>A network built on trust.</p><span>© 2025 Maa Sheetla Agency</span></footer><a className="whatsapp" href="#partner"><MessageCircle size={19}/> WhatsApp</a></main>}
export default App;